### ISSUE TITLE
Not possible to create a new user account - IPT v2.6.1

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/ipt#1845]
Hi @mike-podolskiy90,

After the new IPT version 2.6.1 deployment, I see problems creating new users.  I detected this issue in the [LAC IPT](https://cloud.gbif.org/lac/) and in the [GBIF Test IPT](https://ipt.gbif.org/) as well.

See the following image error and the log error text file attached.
<img width="1387" alt="Screen Shot 2022-10-04 at 12 13 54 PM" src="https://user-images.githubusercontent.com/61566113/193883662-62168159-76e9-462a-b044-2d3f1b6caae6.png">

[log_error_ipt_lac.txt](https://github.com/gbif/ipt/files/9709258/log_error_ipt_lac.txt)

**Comment by mike-podolskiy90** [comment]
Thank you for reporting this! I'm looking into it

**Comment by mike-podolskiy90** [comment]
@leo-buitrago This is fixed, I'll release new version shortly

**Comment by leo-buitrago** [comment]
Thanks @mike-podolskiy90 

However, I'm still seeing this error, on both IPTs. Could be there something wrong with my IPT access?

![image](https://user-images.githubusercontent.com/61566113/194140178-23482ef8-3571-4176-8061-ae5474277433.png)

**Comment by mike-podolskiy90** [comment]
I haven't released new version (2.6.2) yet. It'll also include some more fixes. I'm planning to do that tomorrow.

**Comment by mike-podolskiy90** [comment]
Fixed version has been deployed to cloud.gbif.org
