### ISSUE TITLE
Server error when trying to infer EML data (taxonomic or geographic)

### ISSUE THREAD

**Issue by rukayaj** [gbif/ipt#2081]
When calling https://ipt.gbif.no/manage/metadata-taxcoverage.do?r=symmeio_q4&reinferMetadata=true there's a server error. 

Here's the tail end of the logs: 
```
DEBUG 25-Aug-2023 09:08:31 [org.gbif.ipt.action.portal.ResourceAction] - Loading EML from file: /srv/ipt/resources/marflo_heimdalen/eml-1.3.xml
ERROR 25-Aug-2023 09:08:43 [org.gbif.ipt.service.manage.impl.ResourceManagerImpl] - Error while trying to infer metadata from source data
java.lang.ArrayIndexOutOfBoundsException: 35
	at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.inferMetadata(ResourceManagerImpl.java:2663) ~[classes/:?]
	at org.gbif.ipt.action.manage.MetadataAction.prepare(MetadataAction.java:295) ~[classes/:?]
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:134) ~[classes/:?]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:106) ~[classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:54) ~[classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37) ~[classes/:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133) ~[guice-servlet-4.2.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:8.5.90]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:8.5.90]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:8.5.90]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:8.5.90]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:8.5.90]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:8.5.90]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:8.5.90]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.90]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
DEBUG 25-Aug-2023 09:08:43 [org.gbif.ipt.struts2.IptI18nInterceptor] - Applied request locale: ru
DEBUG 25-Aug-2023 09:08:43 [org.gbif.ipt.action.portal.ResourceAction] - Loading EML from file: /srv/ipt/resources/trom_algae/eml-1.15.xml
DEBUG 25-Aug-2023 09:08:46 [org.gbif.ipt.struts2.IptI18nInterceptor] - Applied request locale: ja
DEBUG 25-Aug-2023 09:08:46 [org.gbif.ipt.action.portal.ResourceAction] - Loading EML from file: /srv/ipt/resources/birdsvikevatnetnorway/eml-1.1.xml
DEBUG 25-Aug-2023 09:08:55 [org.gbif.ipt.action.admin.LogsAction] - Serving logfile /srv/ipt/logs/admin.log
DEBUG 25-Aug-2023 09:08:56 [org.gbif.ipt.action.admin.LogsAction] - Serving logfile /srv/ipt/logs/debug.log
DEBUG 25-Aug-2023 09:08:56 [org.gbif.ipt.action.admin.LogsAction] - Serving logfile /srv/ipt/logs/debug.log
ERROR 25-Aug-2023 09:08:56 [org.apache.struts2.dispatcher.DefaultDispatcherErrorHandler] - Exception occurred during processing request: java.io.IOException: Broken pipe
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:369) ~[catalina.jar:8.5.90]
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:846) ~[catalina.jar:8.5.90]
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:316) ~[catalina.jar:8.5.90]
	at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:268) ~[catalina.jar:8.5.90]
	at org.apache.catalina.connector.CoyoteOutputStream.close(CoyoteOutputStream.java:155) ~[catalina.jar:8.5.90]
	at org.apache.struts2.result.StreamResult.doExecute(StreamResult.java:303) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.result.StrutsResultSupport.execute(StrutsResultSupport.java:206) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.DefaultActionInvocation.executeResult(DefaultActionInvocation.java:375) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:279) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.gbif.ipt.struts2.RequireAdminInterceptor.intercept(RequireAdminInterceptor.java:69) ~[classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:179) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.gbif.ipt.struts2.CsrfLoginInterceptor.intercept(CsrfLoginInterceptor.java:91) ~[classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.validator.ValidationInterceptor.doIntercept(ValidationInterceptor.java:263) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.interceptor.validation.AnnotationValidationInterceptor.doIntercept(AnnotationValidationInterceptor.java:49) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.ConversionErrorInterceptor.doIntercept(ConversionErrorInterceptor.java:142) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:140) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.ParametersInterceptor.doIntercept(ParametersInterceptor.java:140) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.interceptor.MultiselectInterceptor.intercept(MultiselectInterceptor.java:67) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.interceptor.DateTextFieldInterceptor.intercept(DateTextFieldInterceptor.java:133) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.interceptor.CheckboxInterceptor.intercept(CheckboxInterceptor.java:89) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:175) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:134) ~[classes/:?]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:106) ~[classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37) ~[classes/:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133) ~[guice-servlet-4.2.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:8.5.90]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:8.5.90]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:8.5.90]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:8.5.90]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:8.5.90]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:8.5.90]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:8.5.90]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.90]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
Caused by: java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_372]
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:1.8.0_372]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_372]
	at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_372]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470) ~[?:1.8.0_372]
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:136) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1331) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:775) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.SocketWrapperBase.writeBlocking(SocketWrapperBase.java:600) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.SocketWrapperBase.write(SocketWrapperBase.java:544) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:621) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:119) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:227) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.Response.doWrite(Response.java:602) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:356) ~[catalina.jar:8.5.90]
	... 92 more
WARN  25-Aug-2023 09:08:56 [org.apache.struts2.dispatcher.DefaultDispatcherErrorHandler] - Unable to send error response, code: 500; isCommited: true;
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
	at org.apache.catalina.connector.ResponseFacade.checkCommitted(ResponseFacade.java:513) ~[catalina.jar:8.5.90]
	at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:352) ~[catalina.jar:8.5.90]
	at org.apache.struts2.dispatcher.DefaultDispatcherErrorHandler.sendErrorResponse(DefaultDispatcherErrorHandler.java:97) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.DefaultDispatcherErrorHandler.handleError(DefaultDispatcherErrorHandler.java:78) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.Dispatcher.sendError(Dispatcher.java:923) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:589) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79) ~[struts2-core-2.5.30.jar:2.5.30]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141) ~[struts2-core-2.5.30.jar:2.5.30]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37) ~[classes/:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133) ~[guice-servlet-4.2.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:8.5.90]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:8.5.90]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:8.5.90]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:682) ~[catalina.jar:8.5.90]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:8.5.90]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:8.5.90]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:8.5.90]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:8.5.90]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:8.5.90]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.90]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_372]
```

**Comment by mike-podolskiy90** [comment]
Thanks for reporting this bug. I believe it was fixed recently, so if you update to the 2.7.5 it should be fine.

**Comment by mike-podolskiy90** [comment]
https://github.com/gbif/ipt/issues/2056

**Comment by rukayaj** [comment]
Thanks! I just did an update to 2.7.5 and still seeing the same error:

```ERROR 30-Aug-2023 17:32:28 [org.gbif.ipt.service.manage.impl.ResourceManagerImpl] - Error while trying to infer metadata from source data
java.lang.ArrayIndexOutOfBoundsException: 39
	at org.gbif.ipt.service.manage.impl.ResourceManagerImpl.inferMetadata(ResourceManagerImpl.java:2695) ~[classes/:?]
	at org.gbif.ipt.action.manage.MetadataAction.prepare(MetadataAction.java:313) ~[classes/:?]
	at com.opensymphony.xwork2.interceptor.PrepareInterceptor.doIntercept(PrepareInterceptor.java:171) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.interceptor.ServletConfigInterceptor.intercept(ServletConfigInterceptor.java:167) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.opensymphony.xwork2.interceptor.ExceptionMappingInterceptor.intercept(ExceptionMappingInterceptor.java:196) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.interceptor.I18nInterceptor.intercept(I18nInterceptor.java:121) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.gbif.ipt.struts2.RedirectMessageInterceptor.doIntercept(RedirectMessageInterceptor.java:134) ~[classes/:?]
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:99) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.gbif.ipt.struts2.SetupAndCancelInterceptor.intercept(SetupAndCancelInterceptor.java:106) ~[classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.gbif.ipt.struts2.ResourceSessionInterceptor.intercept(ResourceSessionInterceptor.java:54) ~[classes/:?]
	at com.google.inject.struts2.Struts2Factory$ProvidedInterceptor.intercept(Struts2Factory.java:236) ~[guice-struts2-4.2.0.jar:?]
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:249) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:48) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:574) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:79) ~[struts2-core-2.5.31.jar:2.5.31]
	at org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:141) ~[struts2-core-2.5.31.jar:2.5.31]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at org.gbif.ipt.struts2.CorsFilter.doFilter(CorsFilter.java:37) ~[classes/:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) ~[guice-servlet-4.2.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133) ~[guice-servlet-4.2.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181) ~[catalina.jar:8.5.93]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156) ~[catalina.jar:8.5.93]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168) ~[catalina.jar:8.5.93]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:8.5.93]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483) ~[catalina.jar:8.5.93]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) ~[catalina.jar:8.5.93]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[catalina.jar:8.5.93]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:679) ~[catalina.jar:8.5.93]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[catalina.jar:8.5.93]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[catalina.jar:8.5.93]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617) ~[tomcat-coyote.jar:8.5.93]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-coyote.jar:8.5.93]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932) ~[tomcat-coyote.jar:8.5.93]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1694) ~[tomcat-coyote.jar:8.5.93]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-coyote.jar:8.5.93]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-util.jar:8.5.93]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-util.jar:8.5.93]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-util.jar:8.5.93]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]```

Any other ideas? I wonder if it could be caching in some way...

**Comment by mike-podolskiy90** [comment]
Let me check it

**Comment by mike-podolskiy90** [comment]
@rukayaj Can I test the fix with your data/mappings please?

**Comment by rukayaj** [comment]
@mike-podolskiy90 I published a public version here: https://ipt.gbif.no/resource?r=symmeio_q4

**Comment by rukayaj** [comment]
Are you asking for a zip of the resource folder?

**Comment by mike-podolskiy90** [comment]
Yes, please. Or access to the IPT.

**Comment by mike-podolskiy90** [comment]
Thank you for your email, I've managed to test the fix. Now looks fine, I'll include it to the next release, 2.7.6 (probably next week)
